export const CREATE_USER = "CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const USERNAME_AVAILABILITY = "USERNAME_AVAILABILITY";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_FAILED = "AUTHENTICATE_USER_FAILED";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const SAVE_SHOPPING_SUCCESS = "SAVE_SHOPPING_SUCCESS";
export const RESET_CART = "RESET_CART";
export const STARTED_SHOPPING = "STARTED_SHOPPING";
export const FINISHED_SHOPPING = "FINISHED_SHOPPING";
export const PAST_SHOPPING = "PAST_SHOPPING";
export const RESET_SHOPPING = "RESET_SHOPPING";
export const GET_USER_DATA = "GET_USER_DATA";
export const PROCEED_TO_LOGIN = "PROCEED_TO_LOGIN";
export const RESET_USER_DATA = "RESET_USER_DATA";

